version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db_app
    user: postgres
  app:
    container_name: fastapi_app
    build: 
      context: .
    ports:
      - 9999:8000
    depends_on:
      - db